// User Actions
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_IDENTITY_DATA = 'SET_CURRENT_IDENTITY_DATA';
export const SET_ADMIN = 'SET_ADMIN';
export const SET_TEACHER = 'SET_TEACHER';
export const SET_STUDENT = 'SET_STUDENT';
export const LOGIN_USER = 'LOGIN_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const USER_FROM_TOKEN = 'USER_FROM_TOKEN';
export const USER_FROM_TOKEN_SUCCESS = 'USER_FROM_TOKEN_SUCCESS';
export const USER_FROM_TOKEN_FAILURE = 'USER_FROM_TOKEN_FAILURE';
export const RESET_TOKEN = 'RESET_TOKEN';
export const ADMIN_INIT = 'ADMIN_INIT';
export const ADMIN_INIT_FAILURE = 'ADMIN_INIT_FAILURE';

// Course Actions
export const GET_COURSES = 'GET_COURSES';
export const GET_COURSE_FAILURE = 'GET_COURSE_FAILURE';
export const ADD_COURSE = 'ADD_COURSE';
export const ADD_COURSE_FAILURE = 'ADD_COURSE_FAILURE';
export const COURSE_ADD_STUDENT = 'COURSE_ADD_STUDENT';
export const COURSE_ADD_STUDENT_FAILURE = 'COURSE_ADD_STUDENT_FAILURE';
export const COURSE_POST_STUDENT = 'COURSE_POST_STUDENT';
export const COURSE_POST_STUDENT_FAILURE = 'COURSE_POST_STUDENT_FAILURE';
export const COURSE_DELETE_STUDENT = 'COURSE_DELETE_STUDENT';
export const COURSE_DELETE_STUDENT_FAILURE = 'COURSE_DELETE_STUDENT_FAILURE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const UPDATE_COURSE_FAILURE = 'UPDATE_COURSE_FAILURE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const DELETE_COURSE_FAILURE = 'DELETE_COURSE_FAILURE';
export const SELECT_COURSE = 'SELECT_COURSE';
export const SWITCH_MODE = 'SWITCH_MODE';
export const COURSE_ADD_BOOK = 'COURSE_ADD_BOOK';
export const COURSE_REMOVE_BOOK = 'COURSE_REMOVE_BOOK';

// Book Actions
export const GET_BOOKS = 'GET_BOOKS';
export const GET_BOOK_FAILURE = 'GET_BOOK_FAILURE';
export const ADD_BOOK = 'ADD_BOOK';
export const ADD_BOOK_FAILURE = 'ADD_BOOK_FAILURE';
export const UPDATE_BOOK = 'UPDATE_BOOK';
export const UPDATE_BOOK_FAILURE = 'UPDATE_BOOK_FAILURE';
export const DELETE_BOOK = 'DELETE_BOOK';
export const DELETE_BOOK_FAILURE = 'DELETE_BOOK_FAILURE';

// Teacher Actions
export const GET_TEACHERS = 'GET_TEACHERS';
export const GET_TEACHER_FAILURE = 'GET_TEACHER_FAILURE';
export const ADD_TEACHER = 'ADD_TEACHER';
export const ADD_TEACHER_FAILURE = 'ADD_TEACHER_FAILURE';
export const UPDATE_TEACHER = 'UPDATE_TEACHER';
export const UPDATE_TEACHER_FAILURE = 'UPDATE_TEACHER_FAILURE';
export const DELETE_TEACHER = 'DELETE_TEACHER';
export const DELETE_TEACHER_FAILURE = 'DELETE_TEACHER_FAILURE';

// Student Actions
export const GET_STUDENTS = 'GET_STUDENTS';
export const GET_STUDENT_FAILURE = 'GET_STUDENT_FAILURE';
export const ADD_STUDENT = 'ADD_STUDENT';
export const ADD_STUDENT_FAILURE = 'ADD_STUDENT_FAILURE';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const UPDATE_STUDENT_FAILURE = 'UPDATE_STUDENT_FAILURE';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const DELETE_STUDENT_FAILURE = 'DELETE_STUDENT_FAILURE';
export const SELECT_STUDENT = 'SELECT_STUDENT';

// Status Actions
export const SET_ERR_MSG = 'SET_ERR_MSG';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';

// Select books widget actions
export const GROUPED_BOOKS = 'GROUPED_BOOKS';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const SELECT_SERIAL = 'SELECT_SERIAL';
export const RESET_SELECT_BOOKS = 'RESET_SELECT_BOOKS';